### PR TITLE
Release to pypi

### PR DESCRIPTION
**Pull request by janrito**

### CODE REVIEW

**Review by risktoparkrageram — APPROVED** [review]
:robot:

**Review by sam-lawrence — APPROVED** [review]
Great 👍.  

I've created a PYPI api token and added as a secret to this repo.  Hopefully this should just work now?

**Comment by janrito** [comment]
It should, let's give it a try!

**Comment by sam-lawrence** [comment]
Looks like it failed.  I think there may be another project with the same name already...

**Pull request merged**
